### ISSUE TITLE
Socialite

### ISSUE THREAD

**Issue by Gandus10** [HE-Arc/GameHub#10]
Se loguer avec le compte steam en utilisant Socialite de laravel

link : http://socialiteproviders.github.io/providers/steam/

**Comment by Gandus10** [comment]
Pour Laravel 5.5, on doit utiliser la version 2 ou 3 de Socialite, malheureusement Steam n'a pas mis à jour son driver et donc il n'est pas possible de l'utiliser.

**Comment by greut** [comment]
meh? https://github.com/SocialiteProviders/Providers/tree/master/src/Steam

**Comment by Gandus10** [comment]
Done
